# Generated by Django 4.0.1 on 2022-01-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
