# Generated by Django 4.0.1 on 2022-01-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, max_digits=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('testtype', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.DecimalField(decimal_places=0, max_digits=9)),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.DecimalField(decimal_places=0, max_digits=9)),
                ('productid', models.DecimalField(decimal_places=0, max_digits=9)),
                ('orderquantity', models.DecimalField(decimal_places=0, max_digits=20)),
                ('unitprice', models.DecimalField(decimal_places=0, max_digits=20)),
                ('totalprice', models.DecimalField(decimal_places=0, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
