# Generated by Django 4.0.1 on 2022-01-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_transaction_transactiondetail_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='totalprice',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
